In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(5,)

In [9]:
b = np.array([[1], [2], [3], [4], [5]])

In [10]:
b.shape

(5, 1)

In [17]:
a = np.zeros((3, 3), dtype = int)

In [18]:
a.shape

(3, 3)

In [21]:
np.zeros?

In [20]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
b = np.ones((3, 3))

In [23]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
c = np.full((3, 3), 2, dtype=float)

In [33]:
c

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [28]:
np.full?

In [34]:
d = np.eye(4)

In [35]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
rn_mat = np.random.random((3, 3))

In [42]:
rn_mat

array([[0.14626736, 0.21295687, 0.12166403],
       [0.81201277, 0.81822353, 0.40423738],
       [0.61527993, 0.96013174, 0.1297218 ]])

In [38]:
np.random.random?

In [46]:
rn_mat[:, 2]

array([0.12166403, 0.40423738, 0.1297218 ])

In [47]:
d.dtype

dtype('float64')

In [49]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [50]:
x + y

array([[ 6,  8],
       [10, 12]])

In [51]:
x.shape

(2, 2)

In [52]:
x - y

array([[-4, -4],
       [-4, -4]])

In [53]:
x*y

array([[ 5, 12],
       [21, 32]])

In [54]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [55]:
print(np.add(x, y))

[[ 6  8]
 [10 12]]


In [56]:
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]


In [57]:
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]


In [58]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [59]:
np.sqrt(144)

12.0

In [61]:
print(np.matmul(x, y))

[[19 22]
 [43 50]]


In [62]:
print(np.dot(x, y))

[[19 22]
 [43 50]]


In [63]:
np.dot?

In [64]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [87]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])

In [88]:
print(a.dot(b))
print(np.dot(a, b))

91
91


In [89]:
sum(a)

21

In [90]:
np.sum(a)

21

In [91]:
a

array([1, 2, 3, 4, 5, 6])

In [92]:
b

array([1, 2, 3, 4, 5, 6])

In [93]:
b = b**2

In [94]:
b

array([ 1,  4,  9, 16, 25, 36])

In [95]:
np.stack((a, b), axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [96]:
a = np.stack((a, b), axis = 0)

In [101]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  4,  9, 16, 25, 36]])

In [98]:
a.T

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [99]:
a.reshape((6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1,  4],
       [ 9, 16],
       [25, 36]])

In [102]:
a.reshape((4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  4,  9],
       [16, 25, 36]])

In [103]:
a.reshape((3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  1,  4],
       [ 9, 16, 25, 36]])

In [104]:
a.reshape((-1, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  1,  4],
       [ 9, 16, 25, 36]])

In [108]:
a.reshape((4, -1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  4,  9],
       [16, 25, 36]])

In [111]:
a = np.arange(10)

In [113]:
a+=5

In [114]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [115]:
np.arange?

In [119]:
print(np.arange(3, 20, 3))

[ 3  6  9 12 15 18]


In [120]:
np.random.shuffle(a)

In [121]:
a

array([ 9, 12,  8, 13, 11,  6, 14, 10,  7,  5])

In [122]:
a = np.random.rand(2, 3)

In [123]:
a

array([[0.44102912, 0.82873043, 0.59995032],
       [0.667235  , 0.37791019, 0.94224685]])

In [124]:
np.random.rand?

In [128]:
a = np.random.randn(3, 2)

In [129]:
a

array([[-0.0116401 , -1.020449  ],
       [-1.02920148, -0.56567715],
       [ 0.97455867, -0.44540947]])

In [127]:
np.random.randn?

In [130]:
a = np.random.randint(5, 10, 3)

In [131]:
a

array([8, 7, 8])

In [135]:
np.random.randint(5, 100, (5, 5))

array([[51, 66,  8, 29, 88],
       [47, 95,  9, 63, 87],
       [65, 45, 67, 16, 64],
       [42, 30, 54, 26, 94],
       [18, 81, 45, 77,  7]])

In [136]:
arr = np.array([1,2,3,4,5,6,7])

In [146]:
element = np.random.choice(arr)

In [147]:
element

4

In [150]:
a = np.array([[1,2,3,4.0], 
              [7, 8, 9, 10]])

In [155]:
np.min(a, axis = 1)

array([1., 7.])

In [152]:
a.shape

(2, 4)

In [156]:
b = np.array([1,2,3,4,5])

In [157]:
m = sum(b)/5

In [158]:
m

3.0

In [159]:
m = np.mean(b)

In [160]:
m

3.0

In [161]:
m = np.mean(a, axis = 0)

In [162]:
m

array([4., 5., 6., 7.])

In [163]:
m = np.mean(a, axis=1)
print(m)

[2.5 8.5]


In [164]:
print(np.median(a))

5.5


In [170]:
c = np.arange(8)+1

In [171]:
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [174]:
w = np.array([1,2,3,4,5,4,3,2])

In [176]:
np.average(c, weights=w)

4.833333333333333

In [180]:
print(np.mean(c))

4.5


In [181]:
np.average?

In [183]:
c.dot(w)/sum(w)

4.833333333333333

In [192]:
u = np.mean(c)
std_dev = np.sqrt(np.mean(abs(c - u)**2))

In [193]:
std_dev

2.29128784747792

In [194]:
std_dev = np.std(c)

In [195]:
std_dev

2.29128784747792

In [196]:
var = std_dev**2

In [197]:
var

5.25

In [198]:
print(np.var(c))

5.25
