In [34]:
import pandas as pd
import numpy as np

In [32]:
!pip install openpyxl

                                              0.0/250.0 kB ? eta -:--:--
     -------------------------------------- 250.0/250.0 kB 7.7 MB/s eta 0:00:00


In [35]:
user_data = {
    'Marks_A':np.random.randint(50, 100, 5),
    'Marks_B':np.random.randint(50, 100, 5),
    'Marks_C':np.random.randint(50, 100, 5)
}

In [36]:
type(user_data)

dict

In [37]:
df = pd.DataFrame(user_data, dtype='float64')

In [38]:
print(df, type(df))

   Marks_A  Marks_B  Marks_C
0     98.0     65.0     98.0
1     60.0     80.0     59.0
2     76.0     62.0     66.0
3     69.0     91.0     91.0
4     71.0     70.0     97.0 <class 'pandas.core.frame.DataFrame'>


In [39]:
df.head(n = 2)

Marks_A  Marks_B  Marks_C
0     98.0     65.0     98.0
1     60.0     80.0     59.0

In [40]:
df

Marks_A  Marks_B  Marks_C
0     98.0     65.0     98.0
1     60.0     80.0     59.0
2     76.0     62.0     66.0
3     69.0     91.0     91.0
4     71.0     70.0     97.0

In [41]:
df.columns

Index(['Marks_A', 'Marks_B', 'Marks_C'], dtype='object')

In [42]:
df_ = df.to_excel('marks.xlsx')

In [43]:
df.to_excel?

In [47]:
my_data = pd.read_csv('marks.csv')

In [48]:
my_data

Unnamed: 0  Marks_A  Marks_B  Marks_C
0           0     56.0     78.0     72.0
1           1     58.0     99.0     60.0
2           2     83.0     98.0     72.0
3           3     55.0     81.0     55.0
4           4     94.0     96.0     80.0

In [50]:
my_data = my_data.drop(columns=['Unnamed: 0'])

In [52]:
my_data

Marks_A  Marks_B  Marks_C
0     56.0     78.0     72.0
1     58.0     99.0     60.0
2     83.0     98.0     72.0
3     55.0     81.0     55.0
4     94.0     96.0     80.0

In [54]:
my_data.describe()

Marks_A   Marks_B    Marks_C
count   5.000000   5.00000   5.000000
mean   69.200000  90.40000  67.800000
std    18.074844  10.06479  10.109402
min    55.000000  78.00000  55.000000
25%    56.000000  81.00000  60.000000
50%    58.000000  96.00000  72.000000
75%    83.000000  98.00000  72.000000
max    94.000000  99.00000  80.000000

In [74]:
sub_data = my_data.iloc[0]

In [75]:
sub_data

Marks_A    56.0
Marks_B    78.0
Marks_C    72.0
Name: 0, dtype: float64

In [73]:
my_data.iloc?

In [82]:
idx = my_data.columns.get_loc('Marks_A')

In [83]:
idx

0

In [84]:
idx = my_data.columns.get_loc('Marks_C')

In [85]:
idx

2

In [86]:
idx = [my_data.columns.get_loc('Marks_A'), my_data.columns.get_loc('Marks_C')]

In [88]:
idx

[0, 2]

In [87]:
my_data.iloc[3, idx]

Marks_A    55.0
Marks_C    55.0
Name: 3, dtype: float64

In [89]:
my_data

Marks_A  Marks_B  Marks_C
0     56.0     78.0     72.0
1     58.0     99.0     60.0
2     83.0     98.0     72.0
3     55.0     81.0     55.0
4     94.0     96.0     80.0

In [98]:
my_data.sort_values(by = ['Marks_B', 'Marks_A'], ascending=True)

Marks_A  Marks_B  Marks_C
0     56.0     78.0     72.0
3     55.0     81.0     55.0
4     94.0     96.0     80.0
2     83.0     98.0     72.0
1     58.0     99.0     60.0

In [99]:
my_data.sort_values?

In [100]:
type(my_data)

pandas.core.frame.DataFrame

In [101]:
data = my_data.values

In [103]:
print(data, type(data))

[[56. 78. 72.]
 [58. 99. 60.]
 [83. 98. 72.]
 [55. 81. 55.]
 [94. 96. 80.]] <class 'numpy.ndarray'>


In [109]:
new_data = pd.DataFrame(data, dtype='int32', columns=['Marks_A', 'Marks_B', "Marks_C"])

In [110]:
new_data

Marks_A  Marks_B  Marks_C
0       56       78       72
1       58       99       60
2       83       98       72
3       55       81       55
4       94       96       80